settings:
  legacy:
    force: true
    interval: 0s
server:
  status: true
  open: false
  port: 5002
  host: localhost
schema:
  - name: app
    path: .
    commands:
      install:
        status: true
        method: go build -o api
      run:
        status: true
        method: ./api
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
